// ARCHIVO AUTOGENERADO DESDE Question_Option_Variable_Matrix_V1_1.xlsx
// FUENTE OPERATIVA OFICIAL DE SCORING CONGELADA (ALEX IA QUESTIONNAIRE V1.1)
// TOTAL MAPPINGS: 175

import type { QuestionOptionMapping, QuestionOptionKey } from './types.ts';

export const QUESTION_OPTION_MATRIX: QuestionOptionMapping[] = [
  {
    "question_id": "Q01",
    "base_question_id": "Q01",
    "variant_id": "Q01_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_R",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q01",
    "base_question_id": "Q01",
    "variant_id": "Q01_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_I",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q01",
    "base_question_id": "Q01",
    "variant_id": "Q01_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_A",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q01",
    "base_question_id": "Q01",
    "variant_id": "Q01_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_S",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q02",
    "base_question_id": "Q02",
    "variant_id": "Q02_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_R",
    "evidence": 1,
    "question_weight": 0.9,
    "weighted_evidence": 0.9,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q02",
    "base_question_id": "Q02",
    "variant_id": "Q02_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_I",
    "evidence": 1,
    "question_weight": 0.9,
    "weighted_evidence": 0.9,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q02",
    "base_question_id": "Q02",
    "variant_id": "Q02_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_A",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q02",
    "base_question_id": "Q02",
    "variant_id": "Q02_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_E",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q03",
    "base_question_id": "Q03",
    "variant_id": "Q03_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Intereses",
    "variable": "INT_R",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q03",
    "base_question_id": "Q03",
    "variant_id": "Q03_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Intereses",
    "variable": "INT_I",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q03",
    "base_question_id": "Q03",
    "variant_id": "Q03_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Intereses",
    "variable": "INT_A",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q03",
    "base_question_id": "Q03",
    "variant_id": "Q03_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Intereses",
    "variable": "INT_S",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q04",
    "base_question_id": "Q04",
    "variant_id": "Q04_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_R",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q04",
    "base_question_id": "Q04",
    "variant_id": "Q04_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_I",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q04",
    "base_question_id": "Q04",
    "variant_id": "Q04_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_A",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q04",
    "base_question_id": "Q04",
    "variant_id": "Q04_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección forzada",
    "dimension": "Intereses",
    "variable": "INT_E",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q05",
    "base_question_id": "Q05",
    "variant_id": "Q05_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Situación",
    "dimension": "Intereses",
    "variable": "INT_C",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q05",
    "base_question_id": "Q05",
    "variant_id": "Q05_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Situación",
    "dimension": "Intereses",
    "variable": "INT_S",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q05",
    "base_question_id": "Q05",
    "variant_id": "Q05_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Situación",
    "dimension": "Intereses",
    "variable": "APT_CRE",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q05",
    "base_question_id": "Q05",
    "variant_id": "Q05_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Situación",
    "dimension": "Intereses",
    "variable": "INT_E",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q06",
    "base_question_id": "Q06",
    "variant_id": "Q06_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Preferencia",
    "dimension": "Intereses",
    "variable": "INT_C",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q06",
    "base_question_id": "Q06",
    "variant_id": "Q06_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Preferencia",
    "dimension": "Intereses",
    "variable": "INT_I",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q06",
    "base_question_id": "Q06",
    "variant_id": "Q06_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Preferencia",
    "dimension": "Intereses",
    "variable": "INT_A",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q06",
    "base_question_id": "Q06",
    "variant_id": "Q06_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Preferencia",
    "dimension": "Intereses",
    "variable": "INT_E",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q07",
    "base_question_id": "Q07",
    "variant_id": "Q07_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_VAR",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q07",
    "base_question_id": "Q07",
    "variant_id": "Q07_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": null,
    "evidence": 0,
    "question_weight": 1,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q07",
    "base_question_id": "Q07",
    "variant_id": "Q07_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_EST",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q07",
    "base_question_id": "Q07",
    "variant_id": "Q07_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_TEC",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q07",
    "base_question_id": "Q07",
    "variant_id": "Q07_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_PER",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q08",
    "base_question_id": "Q08",
    "variant_id": "Q08_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_PRA",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q08",
    "base_question_id": "Q08",
    "variant_id": "Q08_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.9,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q08",
    "base_question_id": "Q08",
    "variant_id": "Q08_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_EXP",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q08",
    "base_question_id": "Q08",
    "variant_id": "Q08_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_EST",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q09",
    "base_question_id": "Q09",
    "variant_id": "Q09_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_EST",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q09",
    "base_question_id": "Q09",
    "variant_id": "Q09_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_VAR",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q09",
    "base_question_id": "Q09",
    "variant_id": "Q09_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_TEC",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q09",
    "base_question_id": "Q09",
    "variant_id": "Q09_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Preferencias",
    "variable": "PRE_CAM",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q10",
    "base_question_id": "Q10",
    "variant_id": "Q10_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_PER",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q10",
    "base_question_id": "Q10",
    "variant_id": "Q10_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_DAT",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q10",
    "base_question_id": "Q10",
    "variant_id": "Q10_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_PRA",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q10",
    "base_question_id": "Q10",
    "variant_id": "Q10_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección forzada",
    "dimension": "Preferencias",
    "variable": "PRE_EXP",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q11",
    "base_question_id": "Q11",
    "variant_id": "Q11_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Intereses/Preferencias",
    "variable": "INT_C",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q11",
    "base_question_id": "Q11",
    "variant_id": "Q11_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Intereses/Preferencias",
    "variable": "INT_I",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q11",
    "base_question_id": "Q11",
    "variant_id": "Q11_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Intereses/Preferencias",
    "variable": "INT_A",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q11",
    "base_question_id": "Q11",
    "variant_id": "Q11_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Intereses/Preferencias",
    "variable": "INT_E",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q11",
    "base_question_id": "Q11",
    "variant_id": "Q11_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Intereses/Preferencias",
    "variable": "INT_S",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q12",
    "base_question_id": "Q12",
    "variant_id": "Q12_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Preferencia",
    "dimension": "Preferencias",
    "variable": "PRE_TEC",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q12",
    "base_question_id": "Q12",
    "variant_id": "Q12_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Preferencia",
    "dimension": "Preferencias",
    "variable": "PRE_PRA",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q12",
    "base_question_id": "Q12",
    "variant_id": "Q12_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Preferencia",
    "dimension": "Preferencias",
    "variable": "PRE_DAT",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q12",
    "base_question_id": "Q12",
    "variant_id": "Q12_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Preferencia",
    "dimension": "Preferencias",
    "variable": "PRE_PER",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q13",
    "base_question_id": "Q13",
    "variant_id": "Q13_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q13",
    "base_question_id": "Q13",
    "variant_id": "Q13_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_LID",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q13",
    "base_question_id": "Q13",
    "variant_id": "Q13_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": null,
    "evidence": 0,
    "question_weight": 1,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q13",
    "base_question_id": "Q13",
    "variant_id": "Q13_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "APT_ANA",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q14",
    "base_question_id": "Q14",
    "variant_id": "Q14_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_ADA",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q14",
    "base_question_id": "Q14",
    "variant_id": "Q14_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_PER",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q14",
    "base_question_id": "Q14",
    "variant_id": "Q14_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_COL",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q14",
    "base_question_id": "Q14",
    "variant_id": "Q14_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_PER",
    "evidence": -1,
    "question_weight": 1,
    "weighted_evidence": -1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q15",
    "base_question_id": "Q15",
    "variant_id": "Q15_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_SOC",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q15",
    "base_question_id": "Q15",
    "variant_id": "Q15_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": null,
    "evidence": 0,
    "question_weight": 1,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q15",
    "base_question_id": "Q15",
    "variant_id": "Q15_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_AUT",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q15",
    "base_question_id": "Q15",
    "variant_id": "Q15_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q15",
    "base_question_id": "Q15",
    "variant_id": "Q15_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_LID",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q16",
    "base_question_id": "Q16",
    "variant_id": "Q16_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_ADA",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q16",
    "base_question_id": "Q16",
    "variant_id": "Q16_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_ADA",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q16",
    "base_question_id": "Q16",
    "variant_id": "Q16_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PRE_EST",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q16",
    "base_question_id": "Q16",
    "variant_id": "Q16_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": null,
    "evidence": 0,
    "question_weight": 1,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q17",
    "base_question_id": "Q17",
    "variant_id": "Q17_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "APT_ORG",
    "evidence": 1,
    "question_weight": 0.9,
    "weighted_evidence": 0.9,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q17",
    "base_question_id": "Q17",
    "variant_id": "Q17_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_AUT",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q17",
    "base_question_id": "Q17",
    "variant_id": "Q17_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.9,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q17",
    "base_question_id": "Q17",
    "variant_id": "Q17_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q17",
    "base_question_id": "Q17",
    "variant_id": "Q17_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_COL",
    "evidence": 1,
    "question_weight": 0.9,
    "weighted_evidence": 0.9,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q18",
    "base_question_id": "Q18",
    "variant_id": "Q18_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "APT_SOC",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q18",
    "base_question_id": "Q18",
    "variant_id": "Q18_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_COL",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q18",
    "base_question_id": "Q18",
    "variant_id": "Q18_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_LID",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q18",
    "base_question_id": "Q18",
    "variant_id": "Q18_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "PER_AUT",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q18",
    "base_question_id": "Q18",
    "variant_id": "Q18_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Dilema",
    "dimension": "Personalidad",
    "variable": "APT_ANA",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q19",
    "base_question_id": "Q19",
    "variant_id": "Q19_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_AUT",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q19",
    "base_question_id": "Q19",
    "variant_id": "Q19_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_PER",
    "evidence": -1,
    "question_weight": 1,
    "weighted_evidence": -1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q19",
    "base_question_id": "Q19",
    "variant_id": "Q19_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q19",
    "base_question_id": "Q19",
    "variant_id": "Q19_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "APT_VER",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q20",
    "base_question_id": "Q20",
    "variant_id": "Q20_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q20",
    "base_question_id": "Q20",
    "variant_id": "Q20_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_ADA",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q20",
    "base_question_id": "Q20",
    "variant_id": "Q20_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_SOC",
    "evidence": -1,
    "question_weight": 1,
    "weighted_evidence": -1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q20",
    "base_question_id": "Q20",
    "variant_id": "Q20_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_COL",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q21",
    "base_question_id": "Q21",
    "variant_id": "Q21_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_EST",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q21",
    "base_question_id": "Q21",
    "variant_id": "Q21_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": null,
    "evidence": 0,
    "question_weight": 1,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q21",
    "base_question_id": "Q21",
    "variant_id": "Q21_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q21",
    "base_question_id": "Q21",
    "variant_id": "Q21_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario",
    "dimension": "Personalidad",
    "variable": "APT_ANA",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q22",
    "base_question_id": "Q22",
    "variant_id": "Q22_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_LID",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q22",
    "base_question_id": "Q22",
    "variant_id": "Q22_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_INI",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q22",
    "base_question_id": "Q22",
    "variant_id": "Q22_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_COL",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q22",
    "base_question_id": "Q22",
    "variant_id": "Q22_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Elección",
    "dimension": "Personalidad",
    "variable": "PER_AUT",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q23",
    "base_question_id": "Q23",
    "variant_id": "Q23_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_APR",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q23",
    "base_question_id": "Q23",
    "variant_id": "Q23_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_ING",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q23",
    "base_question_id": "Q23",
    "variant_id": "Q23_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_IMP",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q23",
    "base_question_id": "Q23",
    "variant_id": "Q23_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_AUT",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q24",
    "base_question_id": "Q24",
    "variant_id": "Q24_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_CRE",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q24",
    "base_question_id": "Q24",
    "variant_id": "Q24_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_EST",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q24",
    "base_question_id": "Q24",
    "variant_id": "Q24_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_EQV",
    "evidence": 1,
    "question_weight": 0.9,
    "weighted_evidence": 0.9,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q24",
    "base_question_id": "Q24",
    "variant_id": "Q24_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_APR",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q25",
    "base_question_id": "Q25",
    "variant_id": "Q25_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.9,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q25",
    "base_question_id": "Q25",
    "variant_id": "Q25_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.9,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q25",
    "base_question_id": "Q25",
    "variant_id": "Q25_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_IMP",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q25",
    "base_question_id": "Q25",
    "variant_id": "Q25_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_CRE",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q26",
    "base_question_id": "Q26",
    "variant_id": "Q26_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_AUT",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q26",
    "base_question_id": "Q26",
    "variant_id": "Q26_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_EST",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q26",
    "base_question_id": "Q26",
    "variant_id": "Q26_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_AUT",
    "evidence": 1,
    "question_weight": 0.9,
    "weighted_evidence": 0.9,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q26",
    "base_question_id": "Q26",
    "variant_id": "Q26_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_APR",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q27",
    "base_question_id": "Q27",
    "variant_id": "Q27_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_EQV",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q27",
    "base_question_id": "Q27",
    "variant_id": "Q27_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.9,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q27",
    "base_question_id": "Q27",
    "variant_id": "Q27_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_APR",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q27",
    "base_question_id": "Q27",
    "variant_id": "Q27_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Trade-off",
    "dimension": "Valores",
    "variable": "VAL_EQV",
    "evidence": 2,
    "question_weight": 0.9,
    "weighted_evidence": 1.8,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q28",
    "base_question_id": "Q28",
    "variant_id": "Q28_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Escenario de valores",
    "dimension": "Valores",
    "variable": "VAL_REC",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q28",
    "base_question_id": "Q28",
    "variant_id": "Q28_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Escenario de valores",
    "dimension": "Valores",
    "variable": "VAL_APR",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q28",
    "base_question_id": "Q28",
    "variant_id": "Q28_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Escenario de valores",
    "dimension": "Valores",
    "variable": "VAL_CRE",
    "evidence": 2,
    "question_weight": 1,
    "weighted_evidence": 2,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q28",
    "base_question_id": "Q28",
    "variant_id": "Q28_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Escenario de valores",
    "dimension": "Valores",
    "variable": "VAL_IMP",
    "evidence": 1,
    "question_weight": 1,
    "weighted_evidence": 1,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q29",
    "base_question_id": "Q29",
    "variant_id": "Q29_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "A",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_LOG",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q29",
    "base_question_id": "Q29",
    "variant_id": "Q29_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "B",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_LOG",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q29",
    "base_question_id": "Q29",
    "variant_id": "Q29_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "C",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_LOG",
    "evidence": 2,
    "question_weight": 1.25,
    "weighted_evidence": 2.5,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q29",
    "base_question_id": "Q29",
    "variant_id": "Q29_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "C",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_NUM",
    "evidence": 1,
    "question_weight": 1.25,
    "weighted_evidence": 1.25,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q29",
    "base_question_id": "Q29",
    "variant_id": "Q29_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "D",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_LOG",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q30",
    "base_question_id": "Q30",
    "variant_id": "Q30_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "A",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_NUM",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q30",
    "base_question_id": "Q30",
    "variant_id": "Q30_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "B",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_NUM",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q30",
    "base_question_id": "Q30",
    "variant_id": "Q30_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "C",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_LOG",
    "evidence": 1,
    "question_weight": 1.25,
    "weighted_evidence": 1.25,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q30",
    "base_question_id": "Q30",
    "variant_id": "Q30_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "C",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_NUM",
    "evidence": 2,
    "question_weight": 1.25,
    "weighted_evidence": 2.5,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q30",
    "base_question_id": "Q30",
    "variant_id": "Q30_BASE",
    "grade_level": "ALL",
    "difficulty_level": 1,
    "option": "D",
    "question_type": "Mini-reto",
    "dimension": "Aptitud",
    "variable": "APT_NUM",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q31",
    "base_question_id": "Q31",
    "variant_id": "Q31_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "A",
    "question_type": "Mini-reto verbal",
    "dimension": "Aptitud",
    "variable": "APT_VER",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q31",
    "base_question_id": "Q31",
    "variant_id": "Q31_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-reto verbal",
    "dimension": "Aptitud",
    "variable": "APT_ANA",
    "evidence": 1,
    "question_weight": 1.25,
    "weighted_evidence": 1.25,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q31",
    "base_question_id": "Q31",
    "variant_id": "Q31_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-reto verbal",
    "dimension": "Aptitud",
    "variable": "APT_VER",
    "evidence": 2,
    "question_weight": 1.25,
    "weighted_evidence": 2.5,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q31",
    "base_question_id": "Q31",
    "variant_id": "Q31_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "C",
    "question_type": "Mini-reto verbal",
    "dimension": "Aptitud",
    "variable": "APT_VER",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q31",
    "base_question_id": "Q31",
    "variant_id": "Q31_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "D",
    "question_type": "Mini-reto verbal",
    "dimension": "Aptitud",
    "variable": "APT_VER",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q32",
    "base_question_id": "Q32",
    "variant_id": "Q32_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "A",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ANA",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q32",
    "base_question_id": "Q32",
    "variant_id": "Q32_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ANA",
    "evidence": 2,
    "question_weight": 1.1,
    "weighted_evidence": 2.2,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q32",
    "base_question_id": "Q32",
    "variant_id": "Q32_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_LOG",
    "evidence": 1,
    "question_weight": 1.1,
    "weighted_evidence": 1.1,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q32",
    "base_question_id": "Q32",
    "variant_id": "Q32_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "C",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ANA",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q32",
    "base_question_id": "Q32",
    "variant_id": "Q32_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "D",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ANA",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q33",
    "base_question_id": "Q33",
    "variant_id": "Q33_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "A",
    "question_type": "Mini-reto espacial",
    "dimension": "Aptitud",
    "variable": "APT_ESP",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q33",
    "base_question_id": "Q33",
    "variant_id": "Q33_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-reto espacial",
    "dimension": "Aptitud",
    "variable": "APT_ESP",
    "evidence": 2,
    "question_weight": 1.25,
    "weighted_evidence": 2.5,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q33",
    "base_question_id": "Q33",
    "variant_id": "Q33_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "C",
    "question_type": "Mini-reto espacial",
    "dimension": "Aptitud",
    "variable": "APT_ESP",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q33",
    "base_question_id": "Q33",
    "variant_id": "Q33_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "D",
    "question_type": "Mini-reto espacial",
    "dimension": "Aptitud",
    "variable": "APT_ESP",
    "evidence": -1,
    "question_weight": 1.25,
    "weighted_evidence": -1.25,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q34",
    "base_question_id": "Q34",
    "variant_id": "Q34_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Mini-reto creativo (Experimental)",
    "dimension": "Aptitud",
    "variable": null,
    "evidence": 0,
    "question_weight": 0,
    "weighted_evidence": 0,
    "mapping_status": "EXPERIMENTAL_RECORD_ONLY",
    "objective_correct": false
  },
  {
    "question_id": "Q34",
    "base_question_id": "Q34",
    "variant_id": "Q34_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Mini-reto creativo (Experimental)",
    "dimension": "Aptitud",
    "variable": null,
    "evidence": 0,
    "question_weight": 0,
    "weighted_evidence": 0,
    "mapping_status": "EXPERIMENTAL_RECORD_ONLY",
    "objective_correct": false
  },
  {
    "question_id": "Q34",
    "base_question_id": "Q34",
    "variant_id": "Q34_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Mini-reto creativo (Experimental)",
    "dimension": "Aptitud",
    "variable": null,
    "evidence": 0,
    "question_weight": 0,
    "weighted_evidence": 0,
    "mapping_status": "EXPERIMENTAL_RECORD_ONLY",
    "objective_correct": false
  },
  {
    "question_id": "Q34",
    "base_question_id": "Q34",
    "variant_id": "Q34_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Mini-reto creativo (Experimental)",
    "dimension": "Aptitud",
    "variable": null,
    "evidence": 0,
    "question_weight": 0,
    "weighted_evidence": 0,
    "mapping_status": "EXPERIMENTAL_RECORD_ONLY",
    "objective_correct": false
  },
  {
    "question_id": "Q35",
    "base_question_id": "Q35",
    "variant_id": "Q35_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "A",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ORG",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q35",
    "base_question_id": "Q35",
    "variant_id": "Q35_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ANA",
    "evidence": 1,
    "question_weight": 1.1,
    "weighted_evidence": 1.1,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q35",
    "base_question_id": "Q35",
    "variant_id": "Q35_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ORG",
    "evidence": 2,
    "question_weight": 1.1,
    "weighted_evidence": 2.2,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q35",
    "base_question_id": "Q35",
    "variant_id": "Q35_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "C",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ORG",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q35",
    "base_question_id": "Q35",
    "variant_id": "Q35_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "D",
    "question_type": "Mini-caso",
    "dimension": "Aptitud",
    "variable": "APT_ORG",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q36",
    "base_question_id": "Q36",
    "variant_id": "Q36_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "A",
    "question_type": "Mini-caso social",
    "dimension": "Aptitud",
    "variable": "APT_SOC",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q36",
    "base_question_id": "Q36",
    "variant_id": "Q36_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-caso social",
    "dimension": "Aptitud",
    "variable": "APT_SOC",
    "evidence": 2,
    "question_weight": 1.1,
    "weighted_evidence": 2.2,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q36",
    "base_question_id": "Q36",
    "variant_id": "Q36_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "B",
    "question_type": "Mini-caso social",
    "dimension": "Aptitud",
    "variable": "PER_COL",
    "evidence": 1,
    "question_weight": 1.1,
    "weighted_evidence": 1.1,
    "mapping_status": "REVISED_STRUCTURED",
    "objective_correct": true
  },
  {
    "question_id": "Q36",
    "base_question_id": "Q36",
    "variant_id": "Q36_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "C",
    "question_type": "Mini-caso social",
    "dimension": "Aptitud",
    "variable": "APT_SOC",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q36",
    "base_question_id": "Q36",
    "variant_id": "Q36_BASE",
    "grade_level": "ALL",
    "difficulty_level": 2,
    "option": "D",
    "question_type": "Mini-caso social",
    "dimension": "Aptitud",
    "variable": "APT_SOC",
    "evidence": -1,
    "question_weight": 1.1,
    "weighted_evidence": -1.1,
    "mapping_status": "REVISED_STRUCTURED_INCORRECT",
    "objective_correct": false
  },
  {
    "question_id": "Q37",
    "base_question_id": "Q37",
    "variant_id": "Q37_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "INT_I",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q37",
    "base_question_id": "Q37",
    "variant_id": "Q37_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "INT_R",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q37",
    "base_question_id": "Q37",
    "variant_id": "Q37_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "INT_A",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q37",
    "base_question_id": "Q37",
    "variant_id": "Q37_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "INT_S",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q38",
    "base_question_id": "Q38",
    "variant_id": "Q38_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "PER_ADA",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q38",
    "base_question_id": "Q38",
    "variant_id": "Q38_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.75,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q38",
    "base_question_id": "Q38",
    "variant_id": "Q38_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "APT_CRE",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q38",
    "base_question_id": "Q38",
    "variant_id": "Q38_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "PER_ADA",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q38",
    "base_question_id": "Q38",
    "variant_id": "Q38_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "PRE_CAM",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q39",
    "base_question_id": "Q39",
    "variant_id": "Q39_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "PRE_EST",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q39",
    "base_question_id": "Q39",
    "variant_id": "Q39_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": null,
    "evidence": 0,
    "question_weight": 0.75,
    "weighted_evidence": 0,
    "mapping_status": "NO_EVIDENCE",
    "objective_correct": false
  },
  {
    "question_id": "Q39",
    "base_question_id": "Q39",
    "variant_id": "Q39_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "VAL_IMP",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q39",
    "base_question_id": "Q39",
    "variant_id": "Q39_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Consistencia",
    "dimension": "Consistencia",
    "variable": "PRE_EXP",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "A",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "VAL_APR",
    "evidence": 2,
    "question_weight": 0.75,
    "weighted_evidence": 1.5,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "INT_A",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "B",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "VAL_CRE",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "INT_S",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "C",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "VAL_IMP",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "APT_LOG",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  },
  {
    "question_id": "Q40",
    "base_question_id": "Q40",
    "variant_id": "Q40_BASE",
    "grade_level": "ALL",
    "difficulty_level": "",
    "option": "D",
    "question_type": "Integración",
    "dimension": "Integración",
    "variable": "INT_R",
    "evidence": 1,
    "question_weight": 0.75,
    "weighted_evidence": 0.75,
    "mapping_status": "PROPOSED_STRUCTURED",
    "objective_correct": false
  }
];

/**
 * Obtiene los mappings de evidencia para una pregunta y opción seleccionada.
 */
export function getOptionMappings(
  baseQuestionId: string,
  option: QuestionOptionKey
): QuestionOptionMapping[] {
  return QUESTION_OPTION_MATRIX.filter(
    (m) => m.base_question_id === baseQuestionId && m.option === option
  );
}
