/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as PadresRouteImport } from './routes/padres'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrerasSlugRouteImport } from './routes/carreras.$slug'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PadresRoute = PadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasSlugRoute = CarrerasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarrerasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/padres': typeof PadresRoute
  '/resultados': typeof ResultadosRoute
  '/test': typeof TestRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/padres': typeof PadresRoute
  '/resultados': typeof ResultadosRoute
  '/test': typeof TestRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/padres': typeof PadresRoute
  '/resultados': typeof ResultadosRoute
  '/test': typeof TestRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreras'
    | '/padres'
    | '/resultados'
    | '/test'
    | '/carreras/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreras'
    | '/padres'
    | '/resultados'
    | '/test'
    | '/carreras/$slug'
  id:
    | '__root__'
    | '/'
    | '/carreras'
    | '/padres'
    | '/resultados'
    | '/test'
    | '/carreras/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrerasRoute: typeof CarrerasRouteWithChildren
  PadresRoute: typeof PadresRoute
  ResultadosRoute: typeof ResultadosRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padres': {
      id: '/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof PadresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/$slug': {
      id: '/carreras/$slug'
      path: '/$slug'
      fullPath: '/carreras/$slug'
      preLoaderRoute: typeof CarrerasSlugRouteImport
      parentRoute: typeof CarrerasRoute
    }
  }
}

interface CarrerasRouteChildren {
  CarrerasSlugRoute: typeof CarrerasSlugRoute
}

const CarrerasRouteChildren: CarrerasRouteChildren = {
  CarrerasSlugRoute: CarrerasSlugRoute,
}

const CarrerasRouteWithChildren = CarrerasRoute._addFileChildren(
  CarrerasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrerasRoute: CarrerasRouteWithChildren,
  PadresRoute: PadresRoute,
  ResultadosRoute: ResultadosRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
