/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PadresRouteImport } from './routes/padres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamenRouteImport } from './routes/examen'
import { Route as ColegiosRouteImport } from './routes/colegios'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistroPadreRouteImport } from './routes/registro.padre'
import { Route as RegistroEstudianteRouteImport } from './routes/registro.estudiante'
import { Route as CarrerasSlugRouteImport } from './routes/carreras.$slug'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PadresRoute = PadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenRoute = ExamenRouteImport.update({
  id: '/examen',
  path: '/examen',
  getParentRoute: () => rootRouteImport,
} as any)
const ColegiosRoute = ColegiosRouteImport.update({
  id: '/colegios',
  path: '/colegios',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroPadreRoute = RegistroPadreRouteImport.update({
  id: '/registro/padre',
  path: '/registro/padre',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroEstudianteRoute = RegistroEstudianteRouteImport.update({
  id: '/registro/estudiante',
  path: '/registro/estudiante',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasSlugRoute = CarrerasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarrerasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/coach': typeof CoachRoute
  '/colegios': typeof ColegiosRoute
  '/examen': typeof ExamenRoute
  '/login': typeof LoginRoute
  '/padres': typeof PadresRoute
  '/privacidad': typeof PrivacidadRoute
  '/resultados': typeof ResultadosRoute
  '/test': typeof TestRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
  '/registro/estudiante': typeof RegistroEstudianteRoute
  '/registro/padre': typeof RegistroPadreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/coach': typeof CoachRoute
  '/colegios': typeof ColegiosRoute
  '/examen': typeof ExamenRoute
  '/login': typeof LoginRoute
  '/padres': typeof PadresRoute
  '/privacidad': typeof PrivacidadRoute
  '/resultados': typeof ResultadosRoute
  '/test': typeof TestRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
  '/registro/estudiante': typeof RegistroEstudianteRoute
  '/registro/padre': typeof RegistroPadreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/coach': typeof CoachRoute
  '/colegios': typeof ColegiosRoute
  '/examen': typeof ExamenRoute
  '/login': typeof LoginRoute
  '/padres': typeof PadresRoute
  '/privacidad': typeof PrivacidadRoute
  '/resultados': typeof ResultadosRoute
  '/test': typeof TestRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
  '/registro/estudiante': typeof RegistroEstudianteRoute
  '/registro/padre': typeof RegistroPadreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreras'
    | '/coach'
    | '/colegios'
    | '/examen'
    | '/login'
    | '/padres'
    | '/privacidad'
    | '/resultados'
    | '/test'
    | '/carreras/$slug'
    | '/registro/estudiante'
    | '/registro/padre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreras'
    | '/coach'
    | '/colegios'
    | '/examen'
    | '/login'
    | '/padres'
    | '/privacidad'
    | '/resultados'
    | '/test'
    | '/carreras/$slug'
    | '/registro/estudiante'
    | '/registro/padre'
  id:
    | '__root__'
    | '/'
    | '/carreras'
    | '/coach'
    | '/colegios'
    | '/examen'
    | '/login'
    | '/padres'
    | '/privacidad'
    | '/resultados'
    | '/test'
    | '/carreras/$slug'
    | '/registro/estudiante'
    | '/registro/padre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrerasRoute: typeof CarrerasRouteWithChildren
  CoachRoute: typeof CoachRoute
  ColegiosRoute: typeof ColegiosRoute
  ExamenRoute: typeof ExamenRoute
  LoginRoute: typeof LoginRoute
  PadresRoute: typeof PadresRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResultadosRoute: typeof ResultadosRoute
  TestRoute: typeof TestRoute
  RegistroEstudianteRoute: typeof RegistroEstudianteRoute
  RegistroPadreRoute: typeof RegistroPadreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padres': {
      id: '/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof PadresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen': {
      id: '/examen'
      path: '/examen'
      fullPath: '/examen'
      preLoaderRoute: typeof ExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colegios': {
      id: '/colegios'
      path: '/colegios'
      fullPath: '/colegios'
      preLoaderRoute: typeof ColegiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro/padre': {
      id: '/registro/padre'
      path: '/registro/padre'
      fullPath: '/registro/padre'
      preLoaderRoute: typeof RegistroPadreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro/estudiante': {
      id: '/registro/estudiante'
      path: '/registro/estudiante'
      fullPath: '/registro/estudiante'
      preLoaderRoute: typeof RegistroEstudianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/$slug': {
      id: '/carreras/$slug'
      path: '/$slug'
      fullPath: '/carreras/$slug'
      preLoaderRoute: typeof CarrerasSlugRouteImport
      parentRoute: typeof CarrerasRoute
    }
  }
}

interface CarrerasRouteChildren {
  CarrerasSlugRoute: typeof CarrerasSlugRoute
}

const CarrerasRouteChildren: CarrerasRouteChildren = {
  CarrerasSlugRoute: CarrerasSlugRoute,
}

const CarrerasRouteWithChildren = CarrerasRoute._addFileChildren(
  CarrerasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrerasRoute: CarrerasRouteWithChildren,
  CoachRoute: CoachRoute,
  ColegiosRoute: ColegiosRoute,
  ExamenRoute: ExamenRoute,
  LoginRoute: LoginRoute,
  PadresRoute: PadresRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResultadosRoute: ResultadosRoute,
  TestRoute: TestRoute,
  RegistroEstudianteRoute: RegistroEstudianteRoute,
  RegistroPadreRoute: RegistroPadreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
